// Generated by gencpp from file mobile_robotics/messages.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOTICS_MESSAGE_MESSAGES_H
#define MOBILE_ROBOTICS_MESSAGE_MESSAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_robotics
{
template <class ContainerAllocator>
struct messages_
{
  typedef messages_<ContainerAllocator> Type;

  messages_()
    : seq(0)
    , detections(0)  {
    }
  messages_(const ContainerAllocator& _alloc)
    : seq(0)
    , detections(0)  {
  (void)_alloc;
    }



   typedef int64_t _seq_type;
  _seq_type seq;

   typedef uint8_t _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::mobile_robotics::messages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robotics::messages_<ContainerAllocator> const> ConstPtr;

}; // struct messages_

typedef ::mobile_robotics::messages_<std::allocator<void> > messages;

typedef boost::shared_ptr< ::mobile_robotics::messages > messagesPtr;
typedef boost::shared_ptr< ::mobile_robotics::messages const> messagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robotics::messages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robotics::messages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_robotics::messages_<ContainerAllocator1> & lhs, const ::mobile_robotics::messages_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_robotics::messages_<ContainerAllocator1> & lhs, const ::mobile_robotics::messages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobile_robotics::messages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robotics::messages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robotics::messages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robotics::messages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robotics::messages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robotics::messages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robotics::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c426868eb8f37d0d04ef30507c49cff3";
  }

  static const char* value(const ::mobile_robotics::messages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc426868eb8f37d0dULL;
  static const uint64_t static_value2 = 0x04ef30507c49cff3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robotics::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robotics/messages";
  }

  static const char* value(const ::mobile_robotics::messages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robotics::messages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 seq\n"
"uint8 detections\n"
;
  }

  static const char* value(const ::mobile_robotics::messages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robotics::messages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct messages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robotics::messages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robotics::messages_<ContainerAllocator>& v)
  {
    s << indent << "seq: ";
    Printer<int64_t>::stream(s, indent + "  ", v.seq);
    s << indent << "detections: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detections);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOTICS_MESSAGE_MESSAGES_H
